max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
wrap_comments = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate" 